const PERMISSIONS = {

    APPROVE_ORGANIZATION: "APPROVE_ORGANIZATION",
    REJECT_ORGANIZATION: "REJECT_ORGANIZATION",
    VIEW_ALL_ORGANIZATIONS: "VIEW_ALL_ORGANIZATIONS",

    CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
    UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
    DEACTIVATE_EMPLOYEE: "DEACTIVATE_EMPLOYEE",
    VIEW_EMPLOYEES: "VIEW_EMPLOYEES",

    CREATE_TASK: "CREATE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    DELETE_TASK: "DELETE_TASK",
    VIEW_TASKS: "VIEW_TASKS",

    ACCEPT_TASK: "ACCEPT_TASK",
    REJECT_TASK: "REJECT_TASK",
    MARK_AS_COMPLETED: "MARK_AS_COMPLETED",
    MARK_AS_FAILED: "MARK_AS_FAILED",

    UPDATE_ADMIN: "UPDATE_ADMIN",
    UPDATE_ORGANIZATION: "UPDATE_ORGANIZATION",
};

const ROLE_PERMISSIONS = {
    SUPER_ADMIN: [
        PERMISSIONS.APPROVE_ORGANIZATION,
        PERMISSIONS.REJECT_ORGANIZATION,
        PERMISSIONS.VIEW_ALL_ORGANIZATIONS,

        PERMISSIONS.CREATE_EMPLOYEE,
        PERMISSIONS.UPDATE_EMPLOYEE,
        PERMISSIONS.DEACTIVATE_EMPLOYEE,
        PERMISSIONS.VIEW_EMPLOYEES,

        PERMISSIONS.UPDATE_ADMIN,
        PERMISSIONS.UPDATE_ORGANIZATION,

        PERMISSIONS.VIEW_EMPLOYEES,
        PERMISSIONS.CREATE_TASK,
        PERMISSIONS.UPDATE_TASK,
        PERMISSIONS.VIEW_TASKS,
    ],

    ADMIN: [
        PERMISSIONS.CREATE_EMPLOYEE,
        PERMISSIONS.UPDATE_EMPLOYEE,
        PERMISSIONS.DEACTIVATE_EMPLOYEE,
        PERMISSIONS.VIEW_EMPLOYEES,

        PERMISSIONS.CREATE_TASK,
        PERMISSIONS.UPDATE_TASK,
        PERMISSIONS.DELETE_TASK,
        PERMISSIONS.VIEW_TASKS,

        PERMISSIONS.UPDATE_ADMIN,
        PERMISSIONS.UPDATE_ORGANIZATION,
    ],

    EMPLOYEE: [
        PERMISSIONS.VIEW_EMPLOYEES,
        PERMISSIONS.UPDATE_TASK,
        PERMISSIONS.VIEW_TASKS,

        PERMISSIONS.ACCEPT_TASK,
        PERMISSIONS.REJECT_TASK,
        PERMISSIONS.MARK_AS_COMPLETED,
        PERMISSIONS.MARK_AS_FAILED,
    ],
};

export { PERMISSIONS, ROLE_PERMISSIONS };