const PERMISSIONS = {
    // Tasks
    VIEW_TASKS: "VIEW_TASKS",
    VIEW_ALL_TASKS: "VIEW_ALL_TASKS",
    CREATE_TASK: "CREATE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    DELETE_TASK: "DELETE_TASK",
    ACCEPT_TASK: "ACCEPT_TASK",
    MARK_AS_COMPLETED: "MARK_AS_COMPLETED",
    MARK_AS_FAILED: "MARK_AS_FAILED",
    REQUEST_REJECT_TASK: "REQUEST_REJECT_TASK",
    REVIEW_REJECT_TASK: "REVIEW_REJECT_TASK",

    // Employees
    VIEW_EMPLOYEES: "VIEW_EMPLOYEES",
    VIEW_ALL_EMPLOYEES: "VIEW_ALL_EMPLOYEES",
    CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
    UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
    DEACTIVATE_EMPLOYEE: "DEACTIVATE_EMPLOYEE",
    REACTIVATE_EMPLOYEE: "REACTIVATE_EMPLOYEE",

    // Admin
    CREATE_ADMIN: "CREATE_ADMIN",
    UPDATE_ADMIN: "UPDATE_ADMIN",
    DELETE_ADMIN_EMPLOYEE: "DELETE_ADMIN_EMPLOYEE",

    // Organization
    VIEW_ORGANIZATION: "VIEW_ORGANIZATION",
    VIEW_ALL_ORGANIZATIONS: "VIEW_ALL_ORGANIZATIONS",
    UPDATE_ORGANIZATION: "UPDATE_ORGANIZATION",
    DELETE_ORGANIZATION: "DELETE_ORGANIZATION",
    APPROVE_ORGANIZATION: "APPROVE_ORGANIZATION",
    REJECT_ORGANIZATION: "REJECT_ORGANIZATION",
    REVOKE_ORGANIZATION: "REVOKE_ORGANIZATION",
    RE_ACTIVATE_ORGANIZATION: "RE_ACTIVATE_ORGANIZATION",
};


const ROLE_PERMISSIONS = {

    SUPER_ADMIN: [
        // Organization
        PERMISSIONS.APPROVE_ORGANIZATION,
        PERMISSIONS.REJECT_ORGANIZATION,
        PERMISSIONS.REVOKE_ORGANIZATION,
        PERMISSIONS.RE_ACTIVATE_ORGANIZATION,
        PERMISSIONS.DELETE_ORGANIZATION,
        PERMISSIONS.VIEW_ALL_ORGANIZATIONS,
        PERMISSIONS.UPDATE_ORGANIZATION,
        PERMISSIONS.VIEW_ORGANIZATION,

        // Admin
        PERMISSIONS.CREATE_ADMIN,
        PERMISSIONS.UPDATE_ADMIN,
        PERMISSIONS.DELETE_ADMIN_EMPLOYEE,

        // Employees
        PERMISSIONS.VIEW_ALL_EMPLOYEES,
        PERMISSIONS.VIEW_EMPLOYEES,
        PERMISSIONS.CREATE_EMPLOYEE,
        PERMISSIONS.UPDATE_EMPLOYEE,
        PERMISSIONS.DEACTIVATE_EMPLOYEE,
        PERMISSIONS.REACTIVATE_EMPLOYEE,

        // Tasks
        PERMISSIONS.VIEW_ALL_TASKS,
        PERMISSIONS.VIEW_TASKS,
        PERMISSIONS.CREATE_TASK,
        PERMISSIONS.UPDATE_TASK,
    ],

    ADMIN: [
        // Employees
        PERMISSIONS.CREATE_EMPLOYEE,
        PERMISSIONS.UPDATE_EMPLOYEE,
        PERMISSIONS.DEACTIVATE_EMPLOYEE,
        PERMISSIONS.REACTIVATE_EMPLOYEE,
        PERMISSIONS.VIEW_EMPLOYEES,

        // Tasks
        PERMISSIONS.VIEW_ALL_TASKS,
        PERMISSIONS.VIEW_TASKS,
        PERMISSIONS.CREATE_TASK,
        PERMISSIONS.UPDATE_TASK,
        PERMISSIONS.DELETE_TASK,
        PERMISSIONS.REVIEW_REJECT_TASK,

        // Organization/Admin
        PERMISSIONS.UPDATE_ADMIN,
        PERMISSIONS.VIEW_ORGANIZATION,
        PERMISSIONS.UPDATE_ORGANIZATION,
    ],

    EMPLOYEE: [
        // Tasks
        PERMISSIONS.VIEW_TASKS,
        PERMISSIONS.VIEW_ALL_TASKS,
        PERMISSIONS.UPDATE_TASK,
        PERMISSIONS.ACCEPT_TASK,
        PERMISSIONS.MARK_AS_COMPLETED,
        PERMISSIONS.MARK_AS_FAILED,
        PERMISSIONS.REQUEST_REJECT_TASK,

        // Employees
        PERMISSIONS.VIEW_EMPLOYEES,
        PERMISSIONS.UPDATE_EMPLOYEE,

        // Organization
        PERMISSIONS.VIEW_ORGANIZATION,
    ],
};

export { PERMISSIONS, ROLE_PERMISSIONS };